
class Clothing {
    class bruce {
        title = "Tienda de Ropa";
        conditions = "";
        side = "civ";
        uniforms[] = {
            { "NONE", "Quitar Ropa", 0, "" },
			{ "U_C_Poloshirt_blue", "", 250, "" },
			{ "U_C_Poloshirt_burgundy", "", 250, "" },
			{ "U_C_Poloshirt_stripped", "", 250, "" },
			{ "U_C_Poloshirt_tricolour", "", 250, "" },
			{ "U_C_Poloshirt_salmon", "", 250, "" },
			{ "U_C_Poloshirt_redwhite", "", 250, "" },
			{ "U_NikosBody", "", 250, "" },
			{ "U_OrestesBody", "", 250, "" },
			{ "U_IG_Guerilla2_1", "", 1000, "" },
			{ "U_IG_Guerilla2_2", "", 1000, "" },
			{ "U_IG_Guerilla2_3", "", 1000, "" },
			{ "U_IG_Guerilla3_1", "", 500, "" },
			{ "U_BG_Guerilla2_1", "", 1000, "" },
			{ "U_BG_Guerilla2_2", "", 1000, "" },
			{ "U_C_Poor_1", "", 250, "" },
			{ "U_C_WorkerCoveralls", "", 250, "" },
			{ "U_C_HunterBody_grn", "", 250, "" },
			{ "U_C_Poor_shorts_1", "", 250, "" },
			{ "U_NikosAgedBody", "", 500, "" },
			{ "U_C_man_sport_1_F", "", 350, "" },
			{ "U_C_man_sport_2_F", "", 350, "" },
			{ "U_C_man_sport_3_F", "", 350, "" },
			{ "U_C_Man_casual_1_F", "", 500, "" },
			{ "U_C_Man_casual_2_F", "", 500, "" },
			{ "U_C_Man_casual_3_F", "", 500, "" },
			{ "U_C_Man_casual_4_F", "", 500, "" },
			{ "U_C_Man_casual_5_F", "", 500, "" },
			{ "U_C_Man_casual_6_F", "", 500, "" },
			{ "U_O_R_Gorka_01_black_F", "", 1250, "" },
            { "U_I_L_Uniform_01_tshirt_skull_F", "", 1250, "" },
            { "U_I_L_Uniform_01_tshirt_sport_F", "", 1250, "" },
            { "U_I_L_Uniform_01_tshirt_black_F", "", 1250, "" },
            { "U_I_L_Uniform_01_tshirt_olive_F", "", 1250, "" },
            { "U_C_E_LooterJacket_01_F", "", 1250, "" },
            { "U_C_Uniform_Scientist_01_formal_F", "", 1250, "" },
            { "U_C_Uniform_Scientist_01_F", "", 1250, "" },
            { "U_C_Uniform_Scientist_02_F", "", 1250, "" },
            { "U_C_Uniform_Scientist_02_formal_F", "", 1250, "" },
            { "U_C_Uniform_Farmer_01_F", "", 1250, "" },
            { "U_C_ConstructionCoverall_Blue_F", "", 1250, "" },
			{ "U_C_ConstructionCoverall_Black_F", "", 1250, "" },
			{ "U_C_ConstructionCoverall_Red_F", "", 1250, "" },
			{ "U_C_ConstructionCoverall_Vrana_F", "", 1250, "" },
			{ "U_C_Mechanic_01_F", "", 1250, "" },
			{ "U_C_IDAP_Man_Tee_F", "", 1250, "" },
			{ "U_C_IDAP_Man_TeeShorts_F", "", 1250, "" },
			{ "U_C_IDAP_Man_cargo_F", "", 1250, "" },
			{ "U_C_IDAP_Man_casual_F", "", 1250, "" },
			{ "U_C_IDAP_Man_shorts_F", "", 1250, "" },
			{ "U_C_IDAP_Man_Jeans_F", "", 1250, "" },
			{ "U_Marshal", "", 1250, "" },
			{ "U_OrestesBody", "", 1250, "" },
			{ "U_C_Driver_1_yellowF", "", 1250, "" },
			{ "U_C_Driver_1_blue", "", 1250, "" },
			{ "U_C_Driver_1_white", "", 1250, "" },
			{ "U_C_Driver_2", "", 1250, "" },
			{ "U_C_Driver_1", "", 1250, "" },
			{ "U_C_Driver_1_orange", "", 1250, "" },
			{ "U_C_Driver_1_black", "", 1250, "" },
			{ "U_C_Driver_3", "", 1250, "" },
			{ "U_C_Driver_1_red", "", 1250, "" },
			{ "U_C_Driver_1_green", "", 1250, "" },
			{ "U_C_Driver_4", "", 1250, "" },
			{ "U_C_WorkerCoveralls", "", 1250, "" },
			{ "U_C_HunterBody_grn", "", 1250, "" },
			{ "U_C_Scientist", "", 1250, "" },
			{ "U_C_Journalist", "", 1250, "" },
			{ "U_B_survival_uniform", "", 1250, "" },
			{ "U_I_G_Story_Protagonist_F", "", 1250, "" },
			{ "U_Competitor", "", 1250, "" },
			{ "U_I_C_Soldier_Bandit_4_F", "", 1250, "" },
			{ "U_I_C_Soldier_Bandit_3_F", "", 1250, "" },
			{ "U_I_C_Soldier_Bandit_2_F", "", 1250, "" },
			{ "U_I_C_Soldier_Bandit_1_F", "", 1250, "" },
			{ "U_I_C_Soldier_Bandit_5_F", "", 1250, "" }

        };
        headgear[] = {
            { "NONE", "Quitar Sombrero", 0, "" },
            { "H_Cap_red", "", 50, "" },
			{ "H_Cap_blu", "", 50, "" },
			{ "H_Cap_oli", "", 50, "" },
			{ "H_Cap_tan", "", 50, "" },
			{ "H_Cap_blk", "", 50, "" },
			{ "H_Cap_blk_CMMG", "", 50, "" },
			{ "H_Cap_brn_SPECOPS", "", 50, "" },
			{ "H_Cap_tan_specops_US", "", 50, "" },
			{ "H_Cap_khaki_specops_UK", "", 50, "" },
			{ "H_Cap_grn", "", 50, "" },
			{ "H_Cap_blk_ION", "", 50, "" },
			{ "H_Cap_surfer", "", 50, "" },
			{ "H_BandMask_blk", "", 250, "" },
			{ "H_BandMask_khk", "", 250, "" },
			{ "H_BandMask_reaper", "", 250, "" },
			{ "H_BandMask_demon", "", 250, "" },
			{ "H_StrawHat", "", 100, "" },
			{ "H_StrawHat_dark", "", 100, "" },
			{ "H_Hat_blue", "", 100, "" },
			{ "H_Hat_brown", "", 100, "" },
			{ "H_Hat_camo", "", 100, "" },
			{ "H_Hat_grey", "", 100, "" },
			{ "H_Hat_Tinfoil_F","",50,"" },
			{ "H_PASGT_basic_blue_F", "", 100, "" },
			{ "H_PASGT_basic_white_F", "", 100, "" },
			{ "H_PASGT_basic_black_F", "", 100, "" },
			{ "H_PASGT_basic_olive_F", "", 100, "" },
			{ "H_RacingHelmet_1_yellow_F", "", 100, "" },
			{ "H_RacingHelmet_1_blue_F", "", 100, "" },
			{ "H_RacingHelmet_1_white_F", "", 100, "" },
			{ "H_RacingHelmet_2_F", "", 100, "" },
			{ "H_RacingHelmet_1_F", "", 100, "" },
			{ "H_RacingHelmet_1_orange_F", "", 100, "" },
			{ "H_RacingHelmet_1_black_F", "", 100, "" },
			{ "H_RacingHelmet_3_F", "", 100, "" },
			{ "H_RacingHelmet_1_red_F", "", 100, "" },
			{ "H_RacingHelmet_1_green_F", "", 100, "" },
			{ "H_RacingHelmet_4_F", "", 100, "" },
			{ "H_Construction_basic_yellow_F", "", 100, "" },
			{ "H_Construction_headset_yellow_F", "", 100, "" },
			{ "H_Construction_earprot_yellow_F", "", 100, "" },
			{ "H_Construction_basic_white_F", "", 100, "" },
			{ "H_Construction_headset_white_F", "", 100, "" },
			{ "H_Construction_earprot_white_F", "", 100, "" },
			{ "H_Construction_basic_orange_F", "", 100, "" },
			{ "H_Construction_headset_orange_F", "", 100, "" },
			{ "H_Construction_earprot_orange_F", "", 100, "" },
			{ "H_Construction_basic_black_F", "", 100, "" },
			{ "H_Construction_headset_black_F", "", 100, "" },
			{ "H_Construction_earprot_black_F", "", 100, "" },
			{ "H_Construction_basic_red_F", "", 100, "" },
			{ "H_Construction_headset_red_F", "", 100, "" },
			{ "H_Construction_earprot_red_F", "", 100, "" },
			{ "H_Construction_basic_vrana_F", "", 100, "" },
			{ "H_Construction_headset_vrana_F", "", 100, "" },
			{ "H_Construction_earprot_vrana_F", "", 100, "" },
			{ "H_PASGT_basic_blue_press_F", "", 100, "" },
			{ "H_PASGT_neckprot_blue_press_F", "", 100, "" },
			{ "H_Helmet_Skate", "", 100, "" },
			{ "H_Cap_grn_BI", "", 100, "" },
			{ "H_Cap_White_IDAP_F", "", 100, "" },
			{ "H_Cap_blk_CMMG", "", 100, "" },
			{ "H_Cap_usblack", "", 100, "" },
			{ "H_Cap_tan_specops_US", "", 100, "" },
			{ "H_Cap_Orange_IDAP_F", "", 100, "" },
			{ "H_Cap_Black_IDAP_F", "", 100, "" },
			{ "H_Cap_oli_hs", "", 100, "" },
			{ "H_Cap_press", "", 100, "" },
			{ "H_Cap_khaki_specops_UK", "", 100, "" },
			{ "H_Cap_blk_Raven", "", 100, "" },
			{ "H_Cap_brn_SPECOPS", "", 100, "" },
			{ "H_Cap_marshal", "", 100, "" },
			{ "H_MilCap_blue", "", 100, "" },
			{ "H_Cap_headphones", "", 100, "" },
			{ "H_Bandanna_sand", "", 100, "" },
			{ "H_Bandanna_khk_hs", "", 100, "" },
			{ "H_Bandanna_blu", "", 100, "" },
			{ "H_Bandanna_camo", "", 100, "" },
			{ "H_Bandanna_khk", "", 100, "" },
			{ "H_Bandanna_cbr", "", 100, "" },
			{ "H_Bandanna_mcamo", "", 100, "" },
			{ "H_Bandanna_gry", "", 100, "" },
			{ "H_Bandanna_sgg", "", 100, "" },
			{ "H_Bandanna_surfer", "", 100, "" },
			{ "H_Bandanna_surfer_blk", "", 100, "" },
			{ "H_Bandanna_surfer_grn", "", 100, "" },
			{ "H_Hat_checker", "", 100, "" },
			{ "H_HeadBandage_stained_F", "", 100, "" },
			{ "H_HeadBandage_clean_F", "", 100, "" },
			{ "H_HeadBandage_bloody_F", "", 100, "" },
			{ "H_Hat_Safari_olive_F", "", 100, "" },
			{ "H_Hat_Safari_sand_F", "", 100, "" },
			{ "H_StrawHat_dark", "", 100, "" },
			{ "H_StrawHat", "", 100, "" },
			{ "H_Hat_tan", "", 100, "" }
        };
        goggles[] = {
            { "NONE", "Quitar Accesorios", 0, "" },
            { "G_Aviator", "", 150, "" },
            { "G_Spectacles", "", 100, "" },
            { "G_Squares", "", 100, "" },
            { "G_Spectacles_Tinted", "", 100, "" },
            { "G_Lowprofile", "", 100, "" },
            { "G_Shades_Blue", "", 100, "" },
            { "G_Shades_Black", "", 100, "" },
            { "G_Squares_Tinted", "", 100, "" },
            { "G_Lady_Blue", "", 100, "" },
            { "G_Sport_Red", "", 100, "" },
            { "G_Sport_Blackyellow", "", 100, "" },
            { "G_Sport_BlackWhite", "", 100, "" },
            { "G_Sport_Checkered", "", 100, "" },
            { "G_Sport_Blackred", "", 100, "" },
            { "G_Sport_Greenblack", "", 100, "" },
            { "G_Tactical_Black", "", 150, "" },
			{ "G_Tactical_Clear", "", 150, "" },
			{ "G_Bandanna_aviator", "", 300, "" },
			{ "G_Bandanna_beast", "", 150, "" },
			{ "G_Bandanna_khk", "", 150, "" },
			{ "G_Bandanna_sport", "", 250, "" },
			{ "G_Bandanna_tan", "", 150, "" },
			{ "G_Bandanna_blk", "", 150, "" },
			{ "G_Bandanna_oli", "", 150, "" },
			{ "G_Bandanna_shades", "", 150, "" },
			{ "G_Balaclava_combat", "", 400, "" },
			{ "G_Balaclava_lowprofile", "", 400, "" },
			{ "G_Balaclava_blk", "", 150, "" }
        };
        vests[] = {
            { "NONE", "Quitar Chaleco", 0, "" },
			{ "V_HarnessO_brn", "", 2500, "" },
			{ "V_HarnessO_gry", "", 2500, "" },
        };
        backpacks[] = {
            { "NONE", "Quitar Mochila", 0, "" },
			{ "B_Carryall_cbr", "Mochila Invisible", 7000, "" },
            { "B_OutdoorPack_blk", "", 500, "" },
			{ "B_FieldPack_green_F", "", 500, "" },
			{ "B_FieldPack_oucamo", "", 500, "" },
			{ "B_FieldPack_ocamo", "", 500, "" },
			{ "B_FieldPack_taiga_F", "", 500, "" },
			{ "B_FieldPack_oli", "", 500, "" },
			{ "B_FieldPack_blk", "", 500, "" },
			{ "B_FieldPack_ghex_F", "", 500, "" },
			{ "B_FieldPack_cbr", "", 500, "" },
			{ "B_FieldPack_khk", "", 500, "" },
			{ "B_LegStrapBag_coyote_F", "", 1500, "" },
			{ "B_LegStrapBag_black_F", "", 1500, "" },
			{ "B_LegStrapBag_olive_F", "", 1500, "" },
			{ "B_Messenger_Coyote_F", "", 1500, "" },
			{ "B_Messenger_Gray_F", "", 1500, "" },
			{ "B_Messenger_Black_F", "", 1500, "" },
			{ "B_Messenger_Olive_F", "", 1500, "" },
			{ "B_Messenger_IDAP_F", "", 1500, "" },
            { "B_AssaultPack_khk", "", 2000, "" },
            { "B_AssaultPack_dgtl", "", 2000, "" },
            { "B_AssaultPack_rgr", "", 2000, "" },
            { "B_AssaultPack_sgg", "", 2000, "" },
            { "B_AssaultPack_blk", "", 2000, "" },
            { "B_AssaultPack_cbr", "", 2000, "" },
			{ "B_AssaultPack_wdl_F", "", 2000, "" },
			{ "B_AssaultPack_khk", "", 2000, "" },
			{ "B_AssaultPack_eaf_F", "", 2000, "" },
			{ "B_AssaultPack_ocamo", "", 2000, "" },
			{ "B_AssaultPack_mcamo", "", 2000, "" },
			{ "B_AssaultPack_tna_F", "", 2000, "" },
			{ "B_AssaultPack_Kerry", "", 2000, "" },
			{ "B_Carryall_ocamo", "", 7000, "" },
            { "B_Carryall_oucamo", "", 7000, "" },
            { "B_Carryall_oli", "", 7000, "" },
            { "B_Carryall_khk", "", 7000, "" },
			{ "B_CombinationUnitRespirator_01_F","",1000,"" }
        };
    };

    class rop_don {
        title = "Tienda de Ropa Donadores";
        conditions = "license_civ_don";
        side = "";
        uniforms[] = {
            { "NONE", "Quitar Ropa", 0, "" },
			{ "U_BG_Guerrilla_6_1", "", 1500, "" },
			{ "U_B_GEN_Commander_F", "", 1000, "" },
			{ "U_B_GhillieSuit", "", 4000, "" },
			{ "U_O_CombatUniform_ocamo", "", 2000, "" },
			{ "U_O_GhillieSuit", "", 4000, "" },
			{ "U_B_CombatUniform_mcam_worn", "", 2000, "" },
			{ "U_B_CombatUniform_sgg_tshirt", "", 2000, "" },
			{ "U_B_CombatUniform_sgg_vest", "", 2000, "" },
			{ "U_B_SpecopsUniform_sgg", "", 2000, "" },
			{ "U_O_SpecopsUniform_ocamo", "", 2000, "" },
			{ "U_O_SpecopsUniform_blk", "", 2000, "" },
			{ "U_I_CombatUniform", "", 2000, "" },
			{ "U_I_CombatUniform_tshirt", "", 2000, "" },
			{ "U_I_CombatUniform_shortsleeve", "", 2000, "" },
			{ "U_I_GhillieSuit", "", 4000, "" },
			{ "U_I_OfficerUniform", "", 2000, "" },
			{ "U_I_Wetsuit", "", 3000, "" },
			{ "U_O_Wetsuit", "", 3000, "" },
			{ "U_B_Wetsuit", "", 3000, "" },
			{ "U_IG_Guerilla1_1", "", 1500, "" },
			{ "U_IG_Guerilla2_1", "", 1500, "" },
			{ "U_IG_Guerilla2_2", "", 1500, "" },
			{ "U_IG_Guerilla2_3", "", 1500, "" },
			{ "U_IG_Guerilla3_1", "", 1500, "" },
			{ "U_IG_Guerilla3_2", "", 1500, "" },
			{ "U_IG_leader", "", 1500, "" },
			{ "U_BG_Guerilla1_1", "", 1500, "" },
			{ "U_BG_Guerilla2_1", "", 1500, "" },
			{ "U_BG_Guerilla2_2", "", 1500, "" },
			{ "U_BG_Guerilla2_3", "", 1500, "" },
			{ "U_BG_Guerilla3_1", "", 1500, "" },
			{ "U_BG_Guerilla3_2", "", 1500, "" },
			{ "U_BG_leader", "", 1500, "" },
			{ "U_OG_leader", "", 1500, "" },
			{ "U_B_CTRG_1", "", 2000, "" },
			{ "U_B_CTRG_2", "", 2000, "" },
			{ "U_B_CTRG_3", "", 2000, "" },
			{ "U_B_survival_uniform", "", 4000, "" },
			{ "U_B_FullGhillie_lsh", "", 8000, "" },
			{ "U_B_FullGhillie_sard", "", 6000, "" },
			{ "U_B_FullGhillie_ard", "", 8000, "" },
			{ "U_O_FullGhillie_lsh", "", 8000, "" },
			{ "U_O_FullGhillie_sard", "", 8000, "" },
			{ "U_O_FullGhillie_ard", "", 8000, "" },
			{ "U_I_FullGhillie_lsh", "", 8000, "" },
			{ "U_I_FullGhillie_sard", "", 8000, "" },
			{ "U_I_FullGhillie_ard", "", 8000, "" },
			{ "U_OG_Guerrilla_6_1", "", 2000, "" },
			{ "U_B_T_Soldier_F", "", 2000, "" },
			{ "U_B_T_Soldier_AR_F", "", 2000, "" },
			{ "U_B_T_Soldier_SL_F", "", 2000, "" },
			{ "U_B_T_Sniper_F", "", 4000, "" },
			{ "U_B_T_FullGhillie_tna_F", "", 8000, "" },
			{ "U_B_CTRG_Soldier_F", "", 2000, "" },
			{ "U_B_CTRG_Soldier_2_F", "", 2000, "" }, 
			{ "U_B_CTRG_Soldier_3_F", "", 2000, "" },
			{ "U_O_T_Soldier_F", "", 2000, "" },
			{ "U_O_T_Officer_F", "", 2000, "" },
			{ "U_O_T_Sniper_F", "", 4000, "" },
			{ "U_O_T_FullGhillie_tna_F", "", 8000, "" },
			{ "U_O_V_Soldier_Viper_F", "", 6000, "" },
			{ "U_O_V_Soldier_Viper_hex_F", "", 6000, "" },
			{ "U_I_C_Soldier_Para_1_F", "", 2000, "" },
			{ "U_I_C_Soldier_Para_2_F", "", 2000, "" },
			{ "U_I_C_Soldier_Para_3_F", "", 2000, "" },
			{ "U_I_C_Soldier_Para_4_F", "", 2000, "" },
			{ "U_I_C_Soldier_Bandit_1_F", "", 2000, "" },
			{ "U_I_C_Soldier_Bandit_2_F", "", 2000, "" },
			{ "U_I_C_Soldier_Bandit_3_F", "", 2000, "" },
			{ "U_I_C_Soldier_Bandit_4_F", "", 2000, "" },
			{ "U_I_C_Soldier_Camo_F", "", 2000, "" }
        };
        headgear[] = {
            { "NONE", "Quitar Sombrero", 0, "" },
            { "H_HelmetB", "", 1500, "" },
			{ "H_HelmetB_camo", "", 1500, "" },
			{ "H_HelmetB_paint", "", 1500, "" },
			{ "H_Booniehat_khk", "", 500, "" },
			{ "H_Booniehat_oli", "", 500, "" },
			{ "H_Booniehat_indp", "", 500, "" },
			{ "H_Booniehat_mcamo", "", 500, "" },
			{ "H_Booniehat_grn", "", 500, "" },
			{ "H_Booniehat_tan", "", 500, "" },
			{ "H_Booniehat_khk_hs", "", 500, "" },
			{ "H_HelmetSpecB", "", 8000, "" },
			{ "H_HelmetSpecB_paint1", "", 8000, "" },
			{ "H_HelmetSpecB_paint2", "", 8000, "" },
			{ "H_HelmetSpecB_snakeskin", "", 8000, "" },
			{ "H_HelmetSpecB_sand", "", 8000, "" },
			{ "H_HelmetIA", "", 1500, "" },
			{ "H_HelmetB_grass", "", 1500, "" },
			{ "H_HelmetB_snakeskin", "", 1500, "" },
			{ "H_HelmetB_desert", "", 1500, "" },
			{ "H_HelmetB_sand", "", 1500, "" },
            { "H_HelmetB_TI_tna_F", "", 2000, "" },
			{ "H_PilotHelmetFighter_B", "", 3500, "" },
			{ "H_HelmetO_ocamo", "", 3500, "" },
			{ "H_HelmetLeaderO_ocamo", "", 5500, "" },
			{ "H_MilCap_ocamo", "", 500, "" },
			{ "H_MilCap_mcamo", "", 500, "" },
			{ "H_MilCap_oucamo", "", 500, "" },
			{ "H_MilCap_gry", "", 500, "" },
			{ "H_MilCap_dgtl", "", 500, "" },
			{ "H_HelmetO_oucamo", "", 5500, "" },
			{ "H_HelmetLeaderO_oucamo", "", 10000, "" },
			{ "H_HelmetSpecO_ocamo", "", 8000, "" },
			{ "H_HelmetSpecO_blk", "", 8000, "" },
			{ "H_Bandanna_khk_hs", "", 500, "" },
			{ "H_ShemagOpen_khk", "", 500, "" },
			{ "H_ShemagOpen_tan", "", 500, "" },
			{ "H_Shemag_olive", "", 500, "" },
			{ "H_Shemag_olive_hs", "", 500, "" },
			{ "H_Hat_Tinfoil_F","",50, "" }
        };
        goggles[] = {
            { "NONE", "Quitar Accesorios", 0, "" },
            { "G_Aviator", "", 150, "" },
            { "G_Spectacles", "", 100, "" },
            { "G_Squares", "", 100, "" },
            { "G_Spectacles_Tinted", "", 100, "" },
            { "G_Lowprofile", "", 100, "" },
            { "G_Shades_Blue", "", 100, "" },
            { "G_Shades_Black", "", 100, "" },
            { "G_Squares_Tinted", "", 100, "" },
            { "G_Lady_Blue", "", 100, "" },
            { "G_Sport_Red", "", 100, "" },
            { "G_Sport_Blackyellow", "", 100, "" },
            { "G_Sport_BlackWhite", "", 100, "" },
            { "G_Sport_Checkered", "", 100, "" },
            { "G_Sport_Blackred", "", 100, "" },
            { "G_Sport_Greenblack", "", 100, "" },
            { "G_Tactical_Black", "", 150, "" },
			{ "G_Tactical_Clear", "", 150, "" },
			{ "G_Bandanna_aviator", "", 300, "" },
			{ "G_Bandanna_beast", "", 150, "" },
			{ "G_Bandanna_khk", "", 150, "" },
			{ "G_Bandanna_sport", "", 250, "" },
			{ "G_Bandanna_tan", "", 150, "" },
			{ "G_Bandanna_blk", "", 150, "" },
			{ "G_Bandanna_oli", "", 150, "" },
			{ "G_Bandanna_shades", "", 150, "" }, 
			{ "G_Balaclava_combat", "", 400, "" },
            { "G_Balaclava_TI_G_tna_F", "", 400, "" },
			{ "G_Balaclava_lowprofile", "", 400, "" },
			{ "G_Balaclava_blk", "", 150, "" }
        };
        vests[] = {
            { "NONE", "Quitar Chaleco", 0, "" },
            { "V_BandollierB_khk", "", 3000, "" },
			{ "V_BandollierB_cbr", "", 3000, "" },
			{ "V_BandollierB_rgr", "", 3000, "" },
			{ "V_BandollierB_blk", "", 3000, "" },
			{ "V_BandollierB_oli", "", 3000, "" },
			{ "V_Chestrig_khk", "", 4000, "" },
			{ "V_Chestrig_rgr", "", 4000, "" },
			{ "V_Chestrig_blk", "", 4000, "" },
			{ "V_Chestrig_oli", "", 4000, "" },
			{ "V_TacVest_khk", "", 5000, "" },
			{ "V_TacVest_brn", "", 5000, "" },
			{ "V_TacVest_oli", "", 5000, "" },
			{ "V_TacVest_camo", "", 5000, "" },
			{ "V_TacVestIR_blk", "", 5000, "" },
			{ "V_TacVestCamo_khk", "", 5000, "" },
			{ "V_PlateCarrier1_rgr", "", 8000, "" },
			{ "V_PlateCarrierIA1_dgtl", "", 8000, "" },
			{ "V_PlateCarrierIA2_dgtl", "", 8000, "" },
			{ "V_PlateCarrier_Kerry", "", 8000, "" },
			{ "V_PlateCarrierL_CTRG", "", 8000, "" },
			{ "V_PlateCarrier1_tna_F", "", 8000, "" },
			{ "V_PlateCarrier1_rgr_noflag_F", "", 8000, "" },
			{ "V_PlateCarrier2_tna_F", "Cartuchera (tropical) [11.000€]", 11000, "" },
			{ "V_PlateCarrier2_rgr_noflag_F", "Cartuchera (verde, sin bandera) [11.000€]", 11000, "" },
			{ "V_PlateCarrier2_rgr", "Cartuchera (verde) [11.000€]", 11000, "" },
			{ "V_PlateCarrierH_CTRG", "Transporte de Placas CTRG Mk.2 (pesado) [11.000€]", 11000, "" },
			{ "V_PlateCarrierGL_rgr", "Cartuchera de GL (verde) [14.000€]", 14000, "" },
			{ "V_PlateCarrierGL_mtp", "Cartuchera de GL de portaaviones (MTP) [14.000€]", 14000, "" },
			{ "V_PlateCarrierIAGL_dgtl", "Cartuchera de AAF independiente (digital) [14.000€]", 14000, "" },
			{ "V_PlateCarrierIAGL_oli", "Cartuchera de GL para portaaviones de GA (oliva) [14.000€]", 14000, "" },
			{ "V_PlateCarrierGL_tna_F", "Cartuchera de GL (tropical) [14.000€]", 14000, "" },
            { "V_PlateCarrierSpec_rgr", "Equipo especial de portaaviones (verde) [18.000€]", 18000, "" },
			{ "V_PlateCarrierSpec_mtp", "Equipo especial de portaaviones (MTP) [18.000€]", 18000, "" },
			{ "V_PlateCarrierSpec_tna_F", "Cartuchera especial (tropical) [18.000€]", 18000, "" },
			{ "V_RebreatherB", "", 7000, "" },
			{ "V_RebreatherIR", "", 7000, "" },
			{ "V_RebreatherIA", "", 7000, "" },
			{ "V_CarrierRigKBT_01_EAF_F", "", 8000, "" },
			{ "V_CarrierRigKBT_01_Olive_F", "", 8000, "" },
			{ "V_SmershVest_01_F", "", 5000, "" },
			{ "V_SmershVest_01_radio_F", "", 5000, "" },
			{ "V_CarrierRigKBT_01_light_Olive_F", "", 9000, "" }
        };
        backpacks[] = {
            { "NONE", "Quitar Mochila", 0, "" },
            { "B_Carryall_cbr", "Mochila Invisible", 7500, "" },
            { "B_OutdoorPack_blk", "", 500, "" },
            { "B_AssaultPack_khk", "", 2000, "" },
            { "B_AssaultPack_dgtl", "", 2000, "" },
            { "B_AssaultPack_rgr", "", 2000, "" },
            { "B_AssaultPack_sgg", "", 2000, "" },
            { "B_AssaultPack_blk", "", 2000, "" },
            { "B_AssaultPack_cbr", "", 2000, "" },
            { "B_AssaultPack_mcamo", "", 2000, "" },
            { "B_TacticalPack_oli", "", 2500, "" },
            { "B_Kitbag_mcamo", "", 3500, "" },
            { "B_Kitbag_sgg", "", 3500, "" },
            { "B_Kitbag_cbr", "", 3500, "" },
            { "B_FieldPack_blk", "", 5000, "" },
            { "B_FieldPack_ocamo", "", 5000, "" },
            { "B_FieldPack_oucamo", "", 5000, "" },
            { "B_Bergen_sgg", "", 6500, "" },
            { "B_Bergen_mcamo", "", 6500, "" },
            { "B_Bergen_rgr", "", 6500, "" },
            { "B_Bergen_blk", "", 6500, "" },
            { "B_Carryall_ocamo", "", 7500, "" },
            { "B_Carryall_oucamo", "", 7500, "" },
            { "B_Carryall_oli", "", 7500, "" },
            { "B_Carryall_khk", "", 7500, "" },
			{ "B_Parachute", "", 3000, "" },
			{ "B_CombinationUnitRespirator_01_F", "", 1000, "" }
        };
    };

    class banda {
        title = "Tienda de Ropa de Bandas";
        conditions = "";
        side = "civ";
        uniforms[] = {
            { "NONE", "Quitar Ropa", 0, "" },
			{ "U_B_CombatUniform_tshirt_mcam_wdL_f", "", 2000, "" }
        };
        headgear[] = {
            { "NONE", "Quitar Sombrero", 0, "" }
        };
        goggles[] = {
            { "NONE", "Quitar Accesorios", 0, "" },
            { "G_Aviator", "", 150, "" },
            { "G_Spectacles", "", 100, "" },
            { "G_Squares", "", 100, "" },
            { "G_Spectacles_Tinted", "", 100, "" },
            { "G_Lowprofile", "", 100, "" },
            { "G_Shades_Blue", "", 100, "" },
            { "G_Shades_Black", "", 100, "" },
            { "G_Squares_Tinted", "", 100, "" },
            { "G_Lady_Blue", "", 100, "" },
            { "G_Sport_Red", "", 100, "" },
            { "G_Sport_Blackyellow", "", 100, "" },
            { "G_Sport_BlackWhite", "", 100, "" },
            { "G_Sport_Checkered", "", 100, "" },
            { "G_Sport_Blackred", "", 100, "" },
            { "G_Sport_Greenblack", "", 100, "" },
            { "G_Tactical_Black", "", 150, "" },
			{ "G_Tactical_Clear", "", 150, "" },
			{ "G_Bandanna_aviator", "", 300, "" },
			{ "G_Bandanna_beast", "", 150, "" },
			{ "G_Bandanna_khk", "", 150, "" },
			{ "G_Bandanna_sport", "", 250, "" },
			{ "G_Bandanna_tan", "", 150, "" },
			{ "G_Bandanna_blk", "", 150, "" },
			{ "G_Bandanna_oli", "", 150, "" },
			{ "G_Bandanna_shades", "", 150, "" }, 
			{ "G_Balaclava_combat", "", 400, "" },
            { "G_Balaclava_TI_G_tna_F", "", 400, "" },
			{ "G_Balaclava_lowprofile", "", 400, "" },
			{ "G_Balaclava_blk", "", 150, "" }
        };
        vests[] = {
            { "NONE", "Quitar Chaleco", 0, "" },
            { "V_TacVest_khk", "", 5000, "" },
			{ "V_TacVestIR_blk", "", 5000, "" },
			{ "V_DeckCrew_violet_F", "", 1000, "" },
			{ "V_DeckCrew_green_F", "", 1000, "" },
			{ "V_DeckCrew_red_F", "", 1000, "" },
			{ "V_DeckCrew_brown_F", "", 1000, "" },
			{ "V_DeckCrew_white_F", "", 1000, "" },
			{ "V_DeckCrew_blue_F", "", 1000, "" },
			{ "V_DeckCrew_yellow_F", "", 1000, "" }
        };
        backpacks[] = {
            { "NONE", "Quitar Mochila", 0, "" },
            { "B_AssaultPack_blk", "", 2000, "" }
        };
    };

    class cop {
        title = "Tienda de Ropa Policial";
        conditions = "call life_coplevel >= 1";
        side = "";
        uniforms[] = {
            { "NONE", "Quitar Ropa", 0, "" },
            { "U_Rangemaster", "Uniforme de Manga Corta", 500, "call life_coplevel >= 1" },
            { "U_BG_Guerrilla_6_1", "Uniforme de Manga Larga", 500, "call life_coplevel >= 5" },
            { "U_B_CTRG_1", "Uniforme de Comisario", 500, "call life_coplevel >= 12" },
            { "U_B_CombatUniform_mcam", "Uniforme de UEI", 500, "license_cop_uei" },
            { "U_B_HeliPilotCoveralls", "Uniforme de Piloto GAP", 500, "license_cop_gap" },
            { "U_B_Wetsuit", "Uniforme de Buzo", 500, "call life_coplevel >= 1" },
            { "U_Marshal", "Ropa Civil", 500, "license_cop_uco" },
            { "U_BG_Guerilla3_1", "Ropa Civil", 500, "license_cop_uco" },
            { "U_OrestesBody", "Ropa Civil", 500, "license_cop_uco" },
            { "U_I_C_Soldier_Bandit_3_F", "Ropa Civil", 500, "license_cop_uco" },
            { "U_I_C_Soldier_Bandit_2_F", "Ropa Civil", 500, "license_cop_uco" },
            { "U_I_CombatUniform", "Ropa Civil", 500, "license_cop_uco" },
            { "U_C_Uniform_Farmer_01_F", "Ropa Civil", 500, "license_cop_uco" },
            { "U_C_Uniform_Scientist_02_formal_F", "Ropa Civil", 500, "license_cop_uco" },
            { "U_C_Uniform_Scientist_02_F", "Ropa Civil", 500, "license_cop_uco" },
            { "U_C_Uniform_Scientist_01_F", "Ropa Civil", 500, "license_cop_uco" },
            { "U_C_Uniform_Scientist_01_formal_F", "Ropa Civil", 500, "license_cop_uco" },
            { "U_C_E_LooterJacket_01_F", "Ropa Civil", 500, "license_cop_uco" },
            { "U_I_L_Uniform_01_tshirt_sport_F", "Ropa Civil", 500, "license_cop_uco" },
            { "U_I_L_Uniform_01_tshirt_skull_F", "Ropa Civil", 500, "license_cop_uco" },
            { "U_I_L_Uniform_01_tshirt_olive_F", "Ropa Civil", 500, "license_cop_uco" },
            { "U_O_R_Gorka_01_black_F", "Ropa Civil", 500, "license_cop_uco" },
            { "U_B_CTRG_Soldier_urb_3_F", "Ropa Civil", 500, "license_cop_uco" }
        };
        headgear[] = {
            { "NONE", "Quitar Sombrero", 0, "" },
            { "H_Cap_police", "", 500, "call life_coplevel >= 1" },
            { "H_MilCap_blue", "", 500, "call life_coplevel >= 1" },
            { "H_Beret_blk", "Boina Negra", 500, "call life_coplevel >= 7" },
            { "H_Beret_Colonel", "Boina de Comisario", 500, "call life_coplevel >= 12" },
			{ "H_Beret_02", "Boina de Sub Comisario", 500, "call life_coplevel >= 11" },
            { "H_HelmetB", "Casco UEI [1]", 500, "license_cop_uei" },
			{ "H_HelmetSpecB_blk", "Casco UEI [2]", 500, "license_cop_uei" },
			{ "H_HelmetB_light_black", "Casco UEI [3]", 500, "license_cop_uei" },
			{ "H_CrewHelmetHeli_O", "Casco de Piloto [1]", 500, "call life_coplevel >= 1" },
            { "H_PilotHelmetHeli_O", "Casco de Piloto [2]", 500, "call life_coplevel >= 1" },
            { "H_Cap_oli", "Gorra Civil", 100, "license_cop_uco" },
            { "H_Cap_blk_Raven", "Gorra Civil", 100, "license_cop_uco" },
            { "H_Cap_red", "Gorra Civil", 100, "license_cop_uco" }
        };
        goggles[] = {
            { "NONE", "Quitar Accesorios", 0, "" },
            { "G_AirPurifyingRespirator_02_black_F", "", 100, "call life_coplevel >= 1" },
            { "G_Squares", "", 10, "call life_coplevel >= 1" },
            { "G_Shades_Blue", "", 20, "call life_coplevel >= 1" },
            { "G_Sport_Blackred", "", 20, "call life_coplevel >= 1" },
            { "G_Sport_Checkered", "", 20, "call life_coplevel >= 1" },
            { "G_Sport_Blackyellow", "", 20, "call life_coplevel >= 1" },
            { "G_Sport_BlackWhite", "", 20, "call life_coplevel >= 1" },
            { "G_Shades_Black", "", 25, "call life_coplevel >= 1" },
            { "G_Lowprofile", "", 30, "call life_coplevel >= 1" },
            { "G_Combat", "", 55, "call life_coplevel >= 1" },
            { "G_Aviator", "", 100, "call life_coplevel >= 1" },
            { "G_Lady_Mirror", "", 150, "call life_coplevel >= 1" },
            { "G_Lady_Dark", "", 150, "call life_coplevel >= 1" },
            { "G_Diving", "", 150, "license_cop_uei" },
			{ "G_Balaclava_combat", "", 150, "license_cop_uco" },
			{ "G_Balaclava_TI_G_tna_F", "", 150, "license_cop_uco" },
			{ "G_Balaclava_lowprofile", "", 150, "license_cop_uco" },
			{ "G_Balaclava_blk", "", 150, "license_cop_uco" }
        };
        vests[] = {
            { "NONE", "Quitar Chaleco", 0, "" },
            { "V_Rangemaster_belt", "Cinturón de Policía", 500, "call life_coplevel >= 1" },
            { "V_TacVest_blk_POLICE", "", 1200, "call life_coplevel >= 1" },
			{ "V_PlateCarrier1_blk", "", 1500, "call life_coplevel >= 1" },
            { "V_PlateCarrier2_blk", "", 1800, "call life_coplevel >= 1" },
            { "V_PlateCarrierSpec_blk", "Chaleco UEI", 2500, "license_cop_uei" },
            { "V_RebreatherB", "", 1000, "call life_coplevel >= 1" }
        };
        backpacks[] = {
            { "NONE", "Quitar Mochila", 0, "" },
            { "B_Carryall_cbr", "Mochila Invisible", 2000, "call life_coplevel >= 1" },
			{ "B_Carryall_ocamo", "", 2000, "license_cop_uco" },
			{ "B_Carryall_mcamo", "", 2000, "license_cop_uco" },
			{ "B_Carryall_oli", "", 2000, "license_cop_uco" },
			{ "B_Carryall_khk", "", 2000, "license_cop_uco" },
			{ "B_Parachute", "", 1000, "call life_coplevel >= 1" }
        };
    };

    class dive {
        title = "Tienda de Buceo";
        conditions = "license_civ_dive";
        side = "civ";
        uniforms[] = {
            { "NONE", "Quitar Ropa", 0, "" },
            { "U_B_Wetsuit", "", 2000, "" }
        };
        headgear[] = {
            { "NONE", "Quitar Sombrero", 0, "" }
        };
        goggles[] = {
            { "NONE", "Quitar Accesorios", 0, "" },
            { "G_Diving", "", 500, "" }
        };
        vests[] = {
            { "NONE", "Quitar Chaleco", 0, "" },
            { "V_RebreatherB", "", 5000, "" }
        };
        backpacks[] = {
            { "NONE", "Quitar Mochila", 0, "" }
        };
    };

    class reb {
        title = "Tienda de Ropa Rebelde";
        conditions = "license_civ_rebel";
        side = "";
        uniforms[] = {
            { "NONE", "Quitar Ropa", 0, "" },
			{ "U_BG_Guerrilla_6_1", "", 1500, "" },
			{ "U_B_GEN_Commander_F", "", 1000, "" },
			{ "U_B_GhillieSuit", "", 4000, "" },
			{ "U_O_CombatUniform_ocamo", "", 2000, "" },
			{ "U_O_GhillieSuit", "", 4000, "" },
			{ "U_B_CombatUniform_mcam_worn", "", 2000, "" },
			{ "U_B_CombatUniform_sgg_tshirt", "", 2000, "" },
			{ "U_B_CombatUniform_sgg_vest", "", 2000, "" },
			{ "U_B_SpecopsUniform_sgg", "", 2000, "" },
			{ "U_O_SpecopsUniform_ocamo", "", 2000, "" },
			{ "U_O_SpecopsUniform_blk", "", 2000, "" },
			{ "U_I_CombatUniform", "", 2000, "" },
			{ "U_I_CombatUniform_tshirt", "", 2000, "" },
			{ "U_I_CombatUniform_shortsleeve", "", 2000, "" },
			{ "U_I_GhillieSuit", "", 4000, "" },
			{ "U_I_OfficerUniform", "", 2000, "" },
			{ "U_I_Wetsuit", "", 3000, "" },
			{ "U_O_Wetsuit", "", 3000, "" },
			{ "U_B_Wetsuit", "", 3000, "" },
			{ "U_IG_Guerilla1_1", "", 1500, "" },
			{ "U_IG_Guerilla2_1", "", 1500, "" },
			{ "U_IG_Guerilla2_2", "", 1500, "" },
			{ "U_IG_Guerilla2_3", "", 1500, "" },
			{ "U_IG_Guerilla3_1", "", 1500, "" },
			{ "U_IG_Guerilla3_2", "", 1500, "" },
			{ "U_IG_leader", "", 1500, "" },
			{ "U_BG_Guerilla1_1", "", 1500, "" },
			{ "U_BG_Guerilla2_1", "", 1500, "" },
			{ "U_BG_Guerilla2_2", "", 1500, "" },
			{ "U_BG_Guerilla2_3", "", 1500, "" },
			{ "U_BG_Guerilla3_1", "", 1500, "" },
			{ "U_BG_Guerilla3_2", "", 1500, "" },
			{ "U_BG_leader", "", 1500, "" },
			{ "U_OG_leader", "", 1500, "" },
			{ "U_B_CTRG_1", "", 2000, "" },
			{ "U_B_CTRG_2", "", 2000, "" },
			{ "U_B_CTRG_3", "", 2000, "" },
			{ "U_B_survival_uniform", "", 4000, "" },
			{ "U_OG_Guerrilla_6_1", "", 2000, "" },
			{ "U_B_T_Soldier_F", "", 2000, "" },
			{ "U_B_T_Soldier_AR_F", "", 2000, "" },
			{ "U_B_T_Soldier_SL_F", "", 2000, "" },
			{ "U_B_T_Sniper_F", "", 4000, "" },
			{ "U_B_CTRG_Soldier_F", "", 2000, "" },
			{ "U_B_CTRG_Soldier_2_F", "", 2000, "" },
			{ "U_B_CTRG_Soldier_3_F", "", 2000, "" },
			{ "U_O_T_Soldier_F", "", 2000, "" },
			{ "U_O_T_Officer_F", "", 2000, "" },
			{ "U_O_T_Sniper_F", "", 4000, "" },
			{ "U_I_C_Soldier_Para_1_F", "", 2000, "" },
			{ "U_I_C_Soldier_Para_2_F", "", 2000, "" },
			{ "U_I_C_Soldier_Para_3_F", "", 2000, "" },
			{ "U_I_C_Soldier_Para_4_F", "", 2000, "" },
			{ "U_I_C_Soldier_Bandit_1_F", "", 2000, "" },
			{ "U_I_C_Soldier_Bandit_2_F", "", 2000, "" },
			{ "U_I_C_Soldier_Bandit_3_F", "", 2000, "" },
			{ "U_I_C_Soldier_Bandit_4_F", "", 2000, "" },
			{ "U_I_C_Soldier_Camo_F", "", 2000, "" }
        };
        headgear[] = {
            { "NONE", "Quitar Sombrero", 0, "" },
            { "H_HelmetB", "", 1500, "" },
			{ "H_HelmetB_camo", "", 1500, "" },
			{ "H_HelmetB_paint", "", 1500, "" },
			{ "H_Booniehat_khk", "", 500, "" },
			{ "H_Booniehat_oli", "", 500, "" },
			{ "H_Booniehat_indp", "", 500, "" },
			{ "H_Booniehat_mcamo", "", 500, "" },
			{ "H_Booniehat_grn", "", 500, "" },
			{ "H_Booniehat_tan", "", 500, "" },
			{ "H_Booniehat_khk_hs", "", 500, "" },
			{ "H_HelmetSpecB", "", 8000, "" },
			{ "H_HelmetSpecB_paint1", "", 8000, "" },
			{ "H_HelmetSpecB_paint2", "", 8000, "" },
			{ "H_HelmetSpecB_snakeskin", "", 8000, "" },
			{ "H_HelmetSpecB_sand", "", 8000, "" },
			{ "H_HelmetIA", "", 1500, "" },
			{ "H_HelmetB_grass", "", 1500, "" },
			{ "H_HelmetB_snakeskin", "", 1500, "" },
			{ "H_HelmetB_desert", "", 1500, "" },
			{ "H_HelmetB_sand", "", 1500, "" },
            { "H_HelmetB_TI_tna_F", "", 2000, "" },
			{ "H_PilotHelmetFighter_B", "", 3500, "" },
			{ "H_HelmetO_ocamo", "", 3500, "" },
			{ "H_HelmetLeaderO_ocamo", "", 5500, "" },
			{ "H_MilCap_ocamo", "", 500, "" },
			{ "H_MilCap_mcamo", "", 500, "" },
			{ "H_MilCap_oucamo", "", 500, "" },
			{ "H_MilCap_gry", "", 500, "" },
			{ "H_MilCap_dgtl", "", 500, "" },
			{ "H_HelmetO_oucamo", "", 5500, "" },
			{ "H_HelmetLeaderO_oucamo", "", 10000, "" },
			{ "H_HelmetSpecO_ocamo", "", 8000, "" },
			{ "H_HelmetSpecO_blk", "", 8000, "" },
			{ "H_Bandanna_khk_hs", "", 500, "" },
			{ "H_Shemag_olive", "", 500, "" },
			{ "H_Shemag_olive_hs", "", 500, "" },
			{ "H_ShemagOpen_khk", "", 500, "" },
			{ "H_ShemagOpen_tan", "", 500, "" }
        };
        goggles[] = {
            { "NONE", "Quitar Accesorios", 0, "" },
            { "G_Aviator", "", 150, "" },
            { "G_Spectacles", "", 100, "" },
            { "G_Squares", "", 100, "" },
            { "G_Spectacles_Tinted", "", 100, "" },
            { "G_Lowprofile", "", 100, "" },
            { "G_Shades_Blue", "", 100, "" },
            { "G_Shades_Black", "", 100, "" },
            { "G_Squares_Tinted", "", 100, "" },
            { "G_Lady_Blue", "", 100, "" },
            { "G_Sport_Red", "", 100, "" },
            { "G_Sport_Blackyellow", "", 100, "" },
            { "G_Sport_BlackWhite", "", 100, "" },
            { "G_Sport_Checkered", "", 100, "" },
            { "G_Sport_Blackred", "", 100, "" },
            { "G_Sport_Greenblack", "", 100, "" },
            { "G_Tactical_Black", "", 150, "" },
			{ "G_Tactical_Clear", "", 150, "" },
			{ "G_Bandanna_aviator", "", 300, "" },
			{ "G_Bandanna_beast", "", 150, "" },
			{ "G_Bandanna_khk", "", 150, "" },
			{ "G_Bandanna_sport", "", 250, "" },
			{ "G_Bandanna_tan", "", 150, "" },
			{ "G_Bandanna_blk", "", 150, "" },
			{ "G_Bandanna_oli", "", 150, "" },
			{ "G_Bandanna_shades", "", 150, "" },
			{ "G_Balaclava_combat", "", 400, "" },
            { "G_Balaclava_TI_G_tna_F", "", 400, "" },
			{ "G_Balaclava_lowprofile", "", 400, "" },
			{ "G_Balaclava_blk", "", 150, "" }
        };
        vests[] = {
            { "NONE", "Quitar Chaleco", 0, "" },
            { "V_BandollierB_khk", "", 3000, "" },
			{ "V_BandollierB_cbr", "", 3000, "" },
			{ "V_BandollierB_rgr", "", 3000, "" },
			{ "V_BandollierB_blk", "", 3000, "" },
			{ "V_BandollierB_oli", "", 3000, "" },
			{ "V_Chestrig_khk", "", 4000, "" },
			{ "V_Chestrig_rgr", "", 4000, "" },
			{ "V_Chestrig_blk", "", 4000, "" },
			{ "V_Chestrig_oli", "", 4000, "" },
			{ "V_TacVest_khk", "", 5000, "" },
			{ "V_TacVest_brn", "", 5000, "" },
			{ "V_TacVest_oli", "", 5000, "" },
			{ "V_TacVest_camo", "", 5000, "" },
			{ "V_TacVestIR_blk", "", 5000, "" },
			{ "V_TacVestCamo_khk", "", 5000, "" },
			{ "V_PlateCarrier1_rgr", "", 8000, "" },
			{ "V_PlateCarrierIA1_dgtl", "", 8000, "" },
			{ "V_PlateCarrierIA2_dgtl", "", 8000, "" },
			{ "V_PlateCarrier_Kerry", "", 8000, "" },
			{ "V_PlateCarrierL_CTRG", "", 8000, "" },
			{ "V_PlateCarrier1_tna_F", "", 8000, "" },
			{ "V_PlateCarrier1_rgr_noflag_F", "", 8000, "" },
			{ "V_PlateCarrier2_tna_F", "Cartuchera (tropical) [11.000€]", 11000, "" },
			{ "V_PlateCarrier2_rgr_noflag_F", "Cartuchera (verde, sin bandera) [11.000€]", 11000, "" },
			{ "V_PlateCarrier2_rgr", "Cartuchera (verde) [11.000€]", 11000, "" },
			{ "V_PlateCarrierH_CTRG", "Transporte de placas CTRG Mk.2 (pesado) [11.000€]", 11000, "" },
			{ "V_PlateCarrierGL_rgr", "Cartuchera de GL (verde) [14.000€]", 14000, "" },
			{ "V_PlateCarrierGL_mtp", "Equipo de GL de portaaviones (MTP) [14.000€]", 14000, "" },
			{ "V_PlateCarrierIAGL_dgtl", "Cartuchera de AAF independiente (digital) [14.000€]", 14000, "" },
			{ "V_PlateCarrierIAGL_oli", "Equipo de GL para portaaviones de GA (oliva) [14.000€]", 14000, "" },
			{ "V_PlateCarrierGL_tna_F", "Cartuchera de GL (tropical) [14.000]", 14000, "" },
			{ "V_RebreatherB", "", 7000, "" },
			{ "V_RebreatherIR", "", 7000, "" },
			{ "V_RebreatherIA", "", 7000, "" },
			{ "V_CarrierRigKBT_01_EAF_F", "", 8000, "" },
			{ "V_CarrierRigKBT_01_Olive_F", "", 8000, "" },
			{ "V_SmershVest_01_F", "", 5000, "" },
			{ "V_SmershVest_01_radio_F", "", 5000, "" },
			{ "V_CarrierRigKBT_01_light_Olive_F", "", 9000,"" }
        };
        backpacks[] = {
            { "NONE", "Quitar Mochila", 0, "" },
            { "B_Carryall_cbr", "Mochila Invisible", 7500, "" },
            { "B_OutdoorPack_blk", "", 500, "" },
            { "B_AssaultPack_khk", "", 2000, "" },
            { "B_AssaultPack_dgtl", "", 2000, "" },
            { "B_AssaultPack_rgr", "", 2000, "" },
            { "B_AssaultPack_sgg", "", 2000, "" },
            { "B_AssaultPack_blk", "", 2000, "" },
            { "B_AssaultPack_cbr", "", 2000, "" },
            { "B_AssaultPack_mcamo", "", 2000, "" },
            { "B_TacticalPack_oli", "", 2500, "" },
            { "B_Kitbag_mcamo", "", 3500, "" },
            { "B_Kitbag_sgg", "", 3500, "" },
            { "B_Kitbag_cbr", "", 3500, "" },
            { "B_FieldPack_blk", "", 5000, "" },
            { "B_FieldPack_ocamo", "", 5000, "" },
            { "B_FieldPack_oucamo", "", 5000, "" },
            { "B_Bergen_sgg", "", 6500, "" },
            { "B_Bergen_mcamo", "", 6500, "" },
            { "B_Bergen_rgr", "", 6500, "" },
            { "B_Bergen_blk", "", 6500, "" },
            { "B_Carryall_ocamo", "", 7500, "" },
            { "B_Carryall_oucamo", "", 7500, "" },
            { "B_Carryall_oli", "", 7500, "" },
            { "B_Carryall_khk", "", 7500, "" },
			{ "B_Parachute", "", 3000, "" }
        };
    };

    class med_clothing {
        title = "Tienda de Ropa EMS";
        conditions = "call life_mediclevel >= 1";
        side = "";
        uniforms[] = {
            { "NONE", "Quitar Ropa", 0, "" },
            { "U_Rangemaster", "Uniforme de Manga Corta", 500, "call life_mediclevel >= 1" },
            { "U_BG_Guerrilla_6_1", "Uniforme de Manga Larga", 500, "call life_mediclevel >= 3" },
            { "U_B_HeliPilotCoveralls", "Uniforme de Piloto GAR", 500, "license_med_gar" },
            { "U_B_Wetsuit", "Uniforme de Buzo", 500, "call life_mediclevel >= 1" }
        };
        headgear[] = {
            { "NONE", "Quitar Sombrero", 0, "" },
            { "H_Beret_blk", "Boina de Jefe", 500, "call life_mediclevel >= 11" },
			{ "H_CrewHelmetHeli_O", "Casco de Piloto [1]", 500, "call life_mediclevel >= 1" },
            { "H_PilotHelmetHeli_O", "Casco de Piloto [2]", 500, "call life_mediclevel >= 1" }
        };
        goggles[] = {
            { "NONE", "Quitar Accesorios", 0, "" },
            { "G_Shades_Blue", "", 10, "call life_mediclevel >= 1" },
			{ "G_Aviator", "", 150, "call life_mediclevel >= 1" },
            { "G_Spectacles", "", 100, "call life_mediclevel >= 1" },
            { "G_Squares", "", 100, "call life_mediclevel >= 1" },
            { "G_Spectacles_Tinted", "", 100, "call life_mediclevel >= 1" },
            { "G_Lowprofile", "", 100, "call life_mediclevel >= 1" },
            { "G_Shades_Blue", "", 100, "call life_mediclevel >= 1" },
            { "G_Shades_Black", "", 100, "call life_mediclevel >= 1" },
            { "G_Squares_Tinted", "", 100, "call life_mediclevel >= 1" },
            { "G_Lady_Blue", "", 100, "call life_mediclevel >= 1" },
            { "G_Sport_Red", "", 100, "call life_mediclevel >= 1" },
            { "G_Sport_Blackyellow", "", 100, "call life_mediclevel >= 1" },
            { "G_Sport_BlackWhite", "", 100, "call life_mediclevel >= 1" },
            { "G_Sport_Checkered", "", 100, "call life_mediclevel >= 1" },
            { "G_Sport_Blackred", "", 100, "call life_mediclevel >= 1" },
            { "G_Sport_Greenblack", "", 100, "call life_mediclevel >= 1" },
            { "G_Tactical_Black", "", 150, "call life_mediclevel >= 1" },
			{ "G_Tactical_Clear", "", 150, "call life_mediclevel >= 1" },
			{ "G_Respirator_Yellow_F", "", 10, "call life_mediclevel >= 1" },
			{ "G_Respirator_white_F", "", 10, "call life_mediclevel >= 1" },
			{ "G_Shades_Green", "", 100, "call life_mediclevel >= 1" },
            { "G_Shades_Red", "", 100, "call life_mediclevel >= 1" },
			{ "G_Respirator_blue_F", "", 10, "call life_mediclevel >= 1" }
        };
        vests[] = {
            { "NONE", "Quitar Chaleco", 0, "" },
			{ "V_RebreatherB", "", 1000, "call life_mediclevel >= 1" }
        };
        backpacks[] = {
            { "NONE", "Quitar Mochila", 0, "" },
            { "B_Carryall_cbr", "Mochila Invisible", 1000, "call life_mediclevel >= 1" },
			{ "B_Parachute", "Paracaidas", 1500, "call life_mediclevel >= 1" }
        };
    };

    class kart {
        title = "Tienda de Ropa";
        conditions = "";
        side = "civ";
        uniforms[] = {
            { "NONE", "Quitar Ropa", 0, "" },
            { "U_C_Driver_1_black", "", 1500, "" },
            { "U_C_Driver_1_blue", "", 1500, "" },
            { "U_C_Driver_1_red", "", 1500, "" },
            { "U_C_Driver_1_orange", "", 1500, "" },
            { "U_C_Driver_1_green", "", 1500, "" },
            { "U_C_Driver_1_white", "", 1500, "" },
            { "U_C_Driver_1_yellow", "", 1500, "" },
            { "U_C_Driver_2", "", 3500, "" },
            { "U_C_Driver_1", "", 3600, "" },
            { "U_C_Driver_3", "", 3700, "" },
            { "U_C_Driver_4", "", 3700, "" }
        };
        headgear[] = {
            { "NONE", "Quitar Sombrero", 0, "" },
            { "H_RacingHelmet_1_black_F", "", 1000, "" },
            { "H_RacingHelmet_1_red_F", "", 1000, "" },
            { "H_RacingHelmet_1_white_F", "", 1000, "" },
            { "H_RacingHelmet_1_blue_F", "", 1000, "" },
            { "H_RacingHelmet_1_yellow_F", "", 1000, "" },
            { "H_RacingHelmet_1_green_F", "", 1000, "" },
            { "H_RacingHelmet_1_F", "", 2500, "" },
            { "H_RacingHelmet_2_F", "", 2500, "" },
            { "H_RacingHelmet_3_F", "", 2500, "" },
            { "H_RacingHelmet_4_F", "", 2500, "" }
        };
        goggles[] = {
            { "NONE", "Quitar Accesorios", 0, "" }
        };
        vests[] = {
            { "NONE", "Quitar Chaleco", 0, "" }
        };
        backpacks[] = {
            { "NONE", "Quitar Mochila", 0, "" }
        };
    };
};
